### ISSUE TITLE
Completed source files under ./Chapter2_Python/

### ISSUE THREAD

**Issue by dependencyInversion** [franneck94/UdemyML_Template#1]
Hi Jan

I'm currently working on your ML course on Udemy and if I understand it correctly this repo is meant to be a template to work with.
So I wonder that under `./Chapter2_Python/` are already the finished source files that I would expect in the other repo.

Am I right in my assumption?

Thank you very much!

**Comment by dependencyInversion** [comment]
FYI I forked this repo and will just delete those files on my fork. :)

**Comment by franneck94** [comment]
Done.
